region               = "eu-west-2"
domain               = "kloud-native.net"
appsilon_subdomain   = "rshiny"
rds_username         = "test"
rds_password         = "test1234test"
rds_db_name          = "testdb"
rds_instance         = "db.t2.micro"
appsilon_version_tag = "c9a417a"
