---
# yamllint disable rule:line-length

name: CI/CD

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PYTHONUNBUFFERED: "1"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: guivin/pre-commit-terraform:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          pre-commit run --all-files --verbose --show-diff-on-failure --color always
